version: '3.9'

services:
  api-gateway:
    build: ./api-gateway
    volumes:
      - ./api-gateway:/usr/src/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - orders-service
      - admin-service
      - auth-service
    networks:
      - restaurant-network

  auth-service:
    build: ./auth-service
    volumes:
      - ./auth-service:/usr/src/app
      - /app/node_modules
    ports:
      - '3001:3001'
    networks:
      - restaurant-network

  orders-service:
    build: ./orders-service
    volumes:
      - ./orders-service:/usr/src/app
      - /app/node_modules
    ports:
      - '3002:3002'
    networks:
      - restaurant-network

  admin-service:
    build: ./admin-service
    volumes:
      - ./admin-service:/usr/src/app
      - /app/node_modules
    ports:
      - '3003:3003'
    networks:
      - restaurant-network

  db:
    image: postgres:15
    container_name: restaurant-db
    environment:
      POSTGRES_DB: restaurant
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - restaurant-network


# DB replication todo
#  postgresql:
#    image: 'bitnami/postgresql:latest'
#    networks:
#      - app-tier

networks:
  restaurant-network:
    driver: bridge

volumes:
  db-data: